# Generated by Django 3.1 on 2020-08-09 17:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 17, 48, 20, 995113, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 17, 48, 20, 995164, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 17, 48, 20, 995143, tzinfo=utc)),
        ),
    ]
